namespace Antares.Server.Tables;

/// <summary>
/// Pure-function, per-dialect SQL renderers for table-structure DDL
/// (CREATE / ALTER column / index / identifier quoting). Extracted from
/// <see cref="TablesWriteService"/> so the SQL string construction is unit-testable
/// in isolation (offline, no DB) and the service is left as thin orchestration.
///
/// Why these stay hand-rolled rather than SqlSugar DbMaintenance/CodeFirst: an
/// empirical probe (2026-06) confirmed SqlSugar 5.1.4.214's DDL generators are
/// strictly weaker here — they silently drop DEFAULT values, COMMENT, UNSIGNED,
/// COLLATE and decimal scale, break SQLite ALTER, and leave reserved-word columns
/// unquoted in named indexes/PKs. See
/// docs/net-migration/2026-06-12-sqlsugar-conversion-outcome.md.
///
/// All members are <c>internal static</c>; tests reach them via
/// <c>[InternalsVisibleTo("Server.IntegrationTests")]</c> (server/AssemblyInfo.cs).
/// </summary>
internal static class TableDdl
{
    // ---- identifier quoting -------------------------------------------------

    /// <summary>Schema-qualified, dialect-quoted table name. sqlite ignores schema.</summary>
    internal static string QualifyTable(string client, string? schema, string? table)
    {
        var t = table ?? string.Empty;
        var s = schema ?? string.Empty;
        return client switch
        {
            "mssql" => string.IsNullOrEmpty(s) ? $"[{Sanitize(t)}]" : $"[{Sanitize(s)}].[{Sanitize(t)}]",
            "mysql" or "maria" => string.IsNullOrEmpty(s) ? $"`{Sanitize(t)}`" : $"`{Sanitize(s)}`.`{Sanitize(t)}`",
            "pg" => string.IsNullOrEmpty(s) ? $"\"{Sanitize(t)}\"" : $"\"{Sanitize(s)}\".\"{Sanitize(t)}\"",
            _ => $"\"{Sanitize(t)}\""
        };
    }

    /// <summary>Single dialect-quoted identifier.</summary>
    internal static string QuoteIdent(string client, string name) => client switch
    {
        "mssql" => $"[{Sanitize(name)}]",
        "mysql" or "maria" => $"`{Sanitize(name)}`",
        "pg" => $"\"{Sanitize(name)}\"",
        _ => $"\"{Sanitize(name)}\""
    };

    /// <summary>
    /// Denylist strip of quote/terminator chars before embedding an identifier in a
    /// SQL string. NOT parameterization — values (defaults, comments) escape via
    /// `Replace("'", "''")` separately.
    /// </summary>
    internal static string Sanitize(string s) =>
        s.Replace("[", "").Replace("]", "").Replace("`", "").Replace("\"", "").Replace(";", "").Replace("--", "");

    // ---- CREATE TABLE column ------------------------------------------------

    internal static string RenderColumn(string client, NewColumnDef c)
    {
        var name = QuoteIdent(client, c.Name);
        var type = c.Type ?? "VARCHAR(255)";
        var nullable = c.Nullable ? string.Empty : " NOT NULL";
        // An identity/auto-increment column must not also carry a DEFAULT — pg and
        // mssql reject "IDENTITY ... DEFAULT", and it's meaningless on mysql/sqlite.
        var def = (c.AutoIncrement || string.IsNullOrEmpty(c.Default)) ? string.Empty : $" DEFAULT {c.Default}";
        var auto = c.AutoIncrement ? client switch
        {
            "mysql" or "maria" => " AUTO_INCREMENT",
            "mssql" => " IDENTITY(1,1)",
            // pg: was silently dropped — emit an identity column (pg 10+) so the
            // CREATE actually produces an auto-increment column. Keeps the type
            // explicit (vs SERIAL, which replaces the type).
            "pg" => " GENERATED BY DEFAULT AS IDENTITY",
            "sqlite" => " AUTOINCREMENT",
            _ => ""
        } : string.Empty;
        return $"{name} {type}{auto}{nullable}{def}";
    }

    /// <summary>
    /// Full `CREATE TABLE {qualified} (col defs[, PRIMARY KEY (...)])`. Columns are
    /// rendered via <see cref="RenderColumn"/>; a composite PRIMARY KEY clause is
    /// appended when any column has <see cref="NewColumnDef.IsPrimary"/>.
    /// </summary>
    internal static string RenderCreateTable(string client, string qualifiedTable, IReadOnlyList<NewColumnDef> columns)
    {
        var colsSql = string.Join(", ", columns.Select(c => RenderColumn(client, c)));
        var pk = columns.Where(c => c.IsPrimary).Select(c => QuoteIdent(client, c.Name)).ToList();
        if (pk.Count > 0) colsSql += $", PRIMARY KEY ({string.Join(", ", pk)})";
        return $"CREATE TABLE {qualifiedTable} ({colsSql})";
    }

    // ---- ALTER: ADD COLUMN clause ------------------------------------------

    /// <summary>
    /// Renders a single ADD COLUMN clause (no leading `ALTER TABLE x`). Per-flavor
    /// keyword / ordering / modifiers:
    ///   mssql:  ADD [name] TYPE(len)        IDENTITY(1,1) NULL|NOT NULL DEFAULT v
    ///   mysql:  ADD COLUMN `name` TYPE(len) UNSIGNED ZEROFILL NULL|NOT NULL AUTO_INCREMENT DEFAULT v COMMENT '...' COLLATE x AFTER `c`
    ///   pg:     ADD COLUMN "name" TYPE(len) NULL|NOT NULL DEFAULT v
    ///   sqlite: ADD COLUMN "name" TYPE(len) NULL|NOT NULL DEFAULT v
    /// </summary>
    internal static string RenderAddColumnClause(string client, FieldDto f)
    {
        var name = QuoteIdent(client, f.Name);
        var typeUpper = f.Type.ToUpperInvariant();
        var lengthSpec = BuildLengthSpec(f);

        return client switch
        {
            "mssql" => $"ADD {name} {typeUpper}{lengthSpec}"
                + (f.AutoIncrement == true ? " IDENTITY(1,1)" : string.Empty)
                + (f.Nullable == false ? " NOT NULL" : " NULL")
                + RenderDefault(f),

            "mysql" or "maria" => $"ADD COLUMN {name} {typeUpper}{lengthSpec}"
                + (f.Unsigned == true ? " UNSIGNED" : string.Empty)
                + (f.Zerofill == true ? " ZEROFILL" : string.Empty)
                + (f.Nullable == false ? " NOT NULL" : " NULL")
                + (f.AutoIncrement == true ? " AUTO_INCREMENT" : string.Empty)
                + RenderDefault(f)
                + (!string.IsNullOrEmpty(f.Comment) ? $" COMMENT '{f.Comment.Replace("'", "''")}'" : string.Empty)
                + (!string.IsNullOrEmpty(f.Collation) ? $" COLLATE {f.Collation}" : string.Empty)
                + (!string.IsNullOrEmpty(f.OnUpdate) ? $" ON UPDATE {f.OnUpdate}" : string.Empty)
                + (!string.IsNullOrEmpty(f.After) ? $" AFTER `{Sanitize(f.After)}`" : string.Empty),

            "pg" => $"ADD COLUMN {name} {typeUpper}{lengthSpec}"
                + (f.IsArray == true ? "[]" : string.Empty)
                + (f.Nullable == false ? " NOT NULL" : string.Empty)
                + RenderDefault(f),

            _ => $"ADD COLUMN {name} {typeUpper}{lengthSpec}"
                + (f.Nullable == false ? " NOT NULL" : string.Empty)
                + RenderDefault(f),
        };
    }

    /// <summary>
    /// Length/precision spec: `(255)`, `(10,2)`, or `('a','b')` for ENUM/SET.
    /// Picks the first non-empty of enumValues / numLength / charLength /
    /// datePrecision / length.
    /// </summary>
    internal static string BuildLengthSpec(FieldDto f)
    {
        if (!string.IsNullOrEmpty(f.EnumValues))
            return $"({f.EnumValues})";

        var len = f.NumLength ?? f.CharLength ?? f.DatePrecision ?? f.Length;
        if (len is null || len <= 0) return string.Empty;

        return f.NumScale is > 0 ? $"({len},{f.NumScale})" : $"({len})";
    }

    /// <summary>
    /// DEFAULT clause. `null` → no clause; `defaultType == "expression"` → unquoted;
    /// otherwise a single-quote-escaped literal. Inlined (not parameterized) because
    /// ALTER TABLE cannot parameterize column defaults.
    /// </summary>
    internal static string RenderDefault(FieldDto f)
    {
        if (f.Default is null) return string.Empty;
        if (string.Equals(f.DefaultType, "expression", StringComparison.OrdinalIgnoreCase))
            return $" DEFAULT {f.Default}";
        var esc = f.Default.Replace("'", "''");
        return $" DEFAULT '{esc}'";
    }

    // ---- ALTER: CHANGE COLUMN (type / rename / modifiers) ------------------

    /// <summary>
    /// A single DDL statement, optionally parameterized (mssql sp_rename and the
    /// extended-property comment block bind parameters; everything else is inlined).
    /// </summary>
    internal readonly record struct DdlStatement(string Sql, object? Params = null);

    // mssql column-comment add-or-update via extended properties (parameterized).
    private const string MssqlColumnCommentSql = @"
IF EXISTS (
    SELECT 1 FROM sys.extended_properties ep
    JOIN sys.tables t ON ep.major_id = t.object_id
    JOIN sys.schemas s ON t.schema_id = s.schema_id
    JOIN sys.columns c ON c.object_id = t.object_id AND c.column_id = ep.minor_id
    WHERE s.name = @sc AND t.name = @t AND c.name = @c AND ep.name = 'MS_Description'
)
    EXEC sp_updateextendedproperty 'MS_Description', @v, 'SCHEMA', @sc, 'TABLE', @t, 'COLUMN', @c;
ELSE
    EXEC sp_addextendedproperty 'MS_Description', @v, 'SCHEMA', @sc, 'TABLE', @t, 'COLUMN', @c;";

    /// <summary>
    /// Renders the ordered statement sequence for a column type-change / rename /
    /// modifier change, per dialect:
    ///   mysql/maria: single CHANGE COLUMN (rename + type + modifiers in one)
    ///   mssql:       [sp_rename] → ALTER COLUMN type+null → [extended-property comment]
    ///   pg:          [RENAME] → ALTER TYPE → SET/DROP NOT NULL → SET/DROP DEFAULT → [COMMENT]
    ///   sqlite:      RENAME only (type/nullable change needs 6-step recreate — empty list,
    ///                caller logs a warning)
    /// </summary>
    internal static IReadOnlyList<DdlStatement> RenderChangeColumn(
        string client, string qualifiedTable, string table, string? schema, FieldDto f)
    {
        var orgName = string.IsNullOrEmpty(f.OrgName) ? f.Name : f.OrgName;
        var typeUpper = f.Type.ToUpperInvariant();
        var lengthSpec = BuildLengthSpec(f);
        var stmts = new List<DdlStatement>();

        switch (client)
        {
            case "mysql":
            case "maria":
                stmts.Add(new DdlStatement(
                    $"ALTER TABLE {qualifiedTable} CHANGE COLUMN `{Sanitize(orgName)}` `{Sanitize(f.Name)}` {typeUpper}{lengthSpec}"
                    + (f.Unsigned == true ? " UNSIGNED" : string.Empty)
                    + (f.Zerofill == true ? " ZEROFILL" : string.Empty)
                    + (f.Nullable == false ? " NOT NULL" : " NULL")
                    + (f.AutoIncrement == true ? " AUTO_INCREMENT" : string.Empty)
                    + RenderDefault(f)
                    + (!string.IsNullOrEmpty(f.Comment) ? $" COMMENT '{f.Comment.Replace("'", "''")}'" : string.Empty)
                    + (!string.IsNullOrEmpty(f.Collation) ? $" COLLATE {f.Collation}" : string.Empty)
                    + (!string.IsNullOrEmpty(f.OnUpdate) ? $" ON UPDATE {f.OnUpdate}" : string.Empty)));
                break;

            case "mssql":
            {
                if (!string.Equals(orgName, f.Name, StringComparison.Ordinal))
                    stmts.Add(new DdlStatement("EXEC sp_rename @oldname, @newname, 'COLUMN'",
                        new { oldname = $"{Sanitize(table)}.{Sanitize(orgName)}", newname = f.Name }));
                var col = QuoteIdent(client, f.Name);
                stmts.Add(new DdlStatement(
                    $"ALTER TABLE {qualifiedTable} ALTER COLUMN {col} {typeUpper}{lengthSpec}"
                    + (f.Nullable == false ? " NOT NULL" : " NULL")));
                if (!string.IsNullOrEmpty(f.Comment))
                    stmts.Add(new DdlStatement(MssqlColumnCommentSql,
                        new { sc = schema, t = table, c = f.Name, v = f.Comment }));
                break;
            }

            case "pg":
            {
                var col = QuoteIdent(client, f.Name);
                if (!string.Equals(orgName, f.Name, StringComparison.Ordinal))
                    stmts.Add(new DdlStatement(
                        $"ALTER TABLE {qualifiedTable} RENAME COLUMN {QuoteIdent(client, orgName)} TO {col}"));
                var arr = f.IsArray == true ? "[]" : string.Empty;
                stmts.Add(new DdlStatement($"ALTER TABLE {qualifiedTable} ALTER COLUMN {col} TYPE {typeUpper}{lengthSpec}{arr}"));
                stmts.Add(new DdlStatement(f.Nullable == false
                    ? $"ALTER TABLE {qualifiedTable} ALTER COLUMN {col} SET NOT NULL"
                    : $"ALTER TABLE {qualifiedTable} ALTER COLUMN {col} DROP NOT NULL"));
                stmts.Add(new DdlStatement(f.Default is null
                    ? $"ALTER TABLE {qualifiedTable} ALTER COLUMN {col} DROP DEFAULT"
                    : (string.Equals(f.DefaultType, "expression", StringComparison.OrdinalIgnoreCase)
                        ? $"ALTER TABLE {qualifiedTable} ALTER COLUMN {col} SET DEFAULT {f.Default}"
                        : $"ALTER TABLE {qualifiedTable} ALTER COLUMN {col} SET DEFAULT '{f.Default.Replace("'", "''")}'")));
                if (f.Comment is not null)
                    stmts.Add(new DdlStatement($"COMMENT ON COLUMN {qualifiedTable}.{col} IS '{f.Comment.Replace("'", "''")}'"));
                break;
            }

            case "sqlite":
                if (!string.Equals(orgName, f.Name, StringComparison.Ordinal))
                    stmts.Add(new DdlStatement(
                        $"ALTER TABLE {qualifiedTable} RENAME COLUMN \"{Sanitize(orgName)}\" TO \"{Sanitize(f.Name)}\""));
                // type/nullable change → 6-step recreate, unsupported; empty list, caller warns.
                break;
        }
        return stmts;
    }

    // ---- ALTER: ADD INDEX ---------------------------------------------------

    internal static string RenderAddIndexSql(string client, string qualified, IndexDto idx)
    {
        var fields = string.Join(",", idx.Fields.Select(f => QuoteIdent(client, f)));
        return client switch
        {
            "mysql" or "maria" => idx.Type == "PRIMARY"
                ? $"ALTER TABLE {qualified} ADD PRIMARY KEY ({fields})"
                : idx.Type == "UNIQUE"
                    ? $"ALTER TABLE {qualified} ADD UNIQUE INDEX `{Sanitize(idx.Name)}` ({fields})"
                    : $"ALTER TABLE {qualified} ADD INDEX `{Sanitize(idx.Name)}` ({fields})",
            "mssql" => idx.Type == "PRIMARY"
                ? $"ALTER TABLE {qualified} ADD CONSTRAINT [{Sanitize(idx.Name)}] PRIMARY KEY ({fields})"
                : idx.Type == "UNIQUE"
                    ? $"CREATE UNIQUE INDEX [{Sanitize(idx.Name)}] ON {qualified} ({fields})"
                    : $"CREATE INDEX [{Sanitize(idx.Name)}] ON {qualified} ({fields})",
            "pg" => idx.Type == "PRIMARY"
                ? $"ALTER TABLE {qualified} ADD CONSTRAINT \"{Sanitize(idx.Name)}\" PRIMARY KEY ({fields})"
                : idx.Type == "UNIQUE"
                    ? $"CREATE UNIQUE INDEX \"{Sanitize(idx.Name)}\" ON {qualified} ({fields})"
                    : $"CREATE INDEX \"{Sanitize(idx.Name)}\" ON {qualified} ({fields})",
            "sqlite" => idx.Type == "UNIQUE"
                ? $"CREATE UNIQUE INDEX \"{Sanitize(idx.Name)}\" ON {qualified} ({fields})"
                : $"CREATE INDEX \"{Sanitize(idx.Name)}\" ON {qualified} ({fields})",
            _ => string.Empty
        };
    }

    /// <summary>
    /// DROP index per dialect. mysql distinguishes PRIMARY (DROP PRIMARY KEY) from a
    /// named index (DROP INDEX); mssql needs the `ON table`; pg/sqlite use
    /// DROP INDEX IF EXISTS. Uses the index's (possibly old) name verbatim.
    /// </summary>
    internal static string RenderDropIndexSql(string client, string qualified, IndexDto idx) => client switch
    {
        "mysql" or "maria" => idx.Type == "PRIMARY"
            ? $"ALTER TABLE {qualified} DROP PRIMARY KEY"
            : $"ALTER TABLE {qualified} DROP INDEX `{Sanitize(idx.Name)}`",
        "mssql" => $"DROP INDEX [{Sanitize(idx.Name)}] ON {qualified}",
        "pg" => $"DROP INDEX IF EXISTS \"{Sanitize(idx.Name)}\"",
        "sqlite" => $"DROP INDEX IF EXISTS \"{Sanitize(idx.Name)}\"",
        _ => string.Empty
    };

    // ---- Duplicate table (structure clone [+ data]) ------------------------

    /// <summary>
    /// Structure-clone statements per dialect (+ an optional data-copy INSERT):
    ///   mssql:  SELECT * INTO dst FROM src WHERE 1=0
    ///   mysql:  CREATE TABLE dst LIKE src
    ///   pg:     CREATE TABLE dst (LIKE src INCLUDING ALL)
    ///   sqlite: CREATE TABLE dst AS SELECT * FROM src WHERE 1=0
    /// Empty list for an unsupported dialect. src/dst must already be qualified+quoted.
    /// </summary>
    internal static IReadOnlyList<string> RenderDuplicate(string client, string srcQualified, string dstQualified, bool copyData)
    {
        var create = client switch
        {
            "mssql" => $"SELECT * INTO {dstQualified} FROM {srcQualified} WHERE 1=0",
            "mysql" or "maria" => $"CREATE TABLE {dstQualified} LIKE {srcQualified}",
            "pg" => $"CREATE TABLE {dstQualified} (LIKE {srcQualified} INCLUDING ALL)",
            "sqlite" => $"CREATE TABLE {dstQualified} AS SELECT * FROM {srcQualified} WHERE 1=0",
            _ => string.Empty
        };
        if (string.IsNullOrEmpty(create)) return System.Array.Empty<string>();
        var stmts = new List<string> { create };
        // All four create structure-only; copy rows separately when requested.
        if (copyData) stmts.Add($"INSERT INTO {dstQualified} SELECT * FROM {srcQualified}");
        return stmts;
    }
}
