using System;
using System.Collections.Generic;
using System.IO;
using Antares.Server.Connections;
using Antares.Server.Models.Connection;
using Antares.Server.Tables;
using SqlSugar;
using Xunit;

namespace Antares.Server.IntegrationTests.Tables;

/// <summary>
/// Characterization tests for TableDdl.RenderCreateTableFromFields / RenderCreateColumnDef
/// — the CREATE TABLE assembly from the renderer's rich FieldDto + an explicit
/// primary-key column list (PK arrives as a PRIMARY entry in the indexes array). Locks
/// per-dialect column rendering, modifiers, the auto-increment keyword (incl. the pg
/// GENERATED ... AS IDENTITY fix and identity-omits-default), and composite PK.
/// </summary>
[Trait("Category", "unit")]
public sealed class TableDdlCreateTests
{
    private static List<FieldDto> IdName(bool idAuto = true) => new()
    {
        new FieldDto { Name = "id", Type = "INT", Nullable = false, AutoIncrement = idAuto },
        new FieldDto { Name = "name", Type = "VARCHAR", CharLength = 100, Nullable = true }
    };
    private static readonly List<string> PkId = new() { "id" };
    private static readonly List<string> NoPk = new();

    [Fact]
    public void Create_mysql_backticks_autoincrement_and_pk()
    {
        var sql = TableDdl.RenderCreateTableFromFields("mysql", "`db`.`User`", IdName(), PkId);
        Assert.StartsWith("CREATE TABLE `db`.`User` (", sql);
        Assert.Contains("`id` INT NOT NULL AUTO_INCREMENT", sql);
        Assert.Contains("`name` VARCHAR(100) NULL", sql);
        Assert.Contains("PRIMARY KEY (`id`)", sql);
    }

    [Fact]
    public void Create_mssql_brackets_identity_and_pk()
    {
        var sql = TableDdl.RenderCreateTableFromFields("mssql", "[dbo].[User]", IdName(), PkId);
        Assert.Contains("[id] INT IDENTITY(1,1) NOT NULL", sql);
        Assert.Contains("PRIMARY KEY ([id])", sql);
    }

    // The pg AUTO_INCREMENT bug fix: pg auto-increment column emits identity (pg 10+).
    [Fact]
    public void Create_pg_emits_identity_for_autoincrement()
    {
        var sql = TableDdl.RenderCreateTableFromFields("pg", "\"public\".\"User\"", IdName(), PkId);
        Assert.Contains("\"id\" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
        Assert.Contains("PRIMARY KEY (\"id\")", sql);
    }

    [Fact]
    public void Create_pg_no_identity_when_not_autoincrement()
    {
        var sql = TableDdl.RenderCreateTableFromFields("pg", "\"t\"", IdName(idAuto: false), PkId);
        Assert.DoesNotContain("IDENTITY", sql);
    }

    [Fact]
    public void Create_sqlite_autoincrement_keyword()
    {
        var sql = TableDdl.RenderCreateTableFromFields("sqlite", "\"User\"", IdName(), PkId);
        Assert.Contains("\"id\" INT AUTOINCREMENT NOT NULL", sql);
    }

    [Fact]
    public void Create_autoincrement_column_omits_default()
    {
        // identity + DEFAULT is invalid on pg/mssql; the auto-increment wins.
        var fields = new List<FieldDto>
        {
            new FieldDto { Name = "id", Type = "INT", Nullable = false, AutoIncrement = true, Default = "0" }
        };
        var sql = TableDdl.RenderCreateTableFromFields("pg", "\"t\"", fields, PkId);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql);
        Assert.DoesNotContain("DEFAULT 0", sql);
    }

    [Fact]
    public void Create_non_identity_column_keeps_default()
    {
        var fields = new List<FieldDto> { new FieldDto { Name = "status", Type = "VARCHAR", CharLength = 20, Default = "active" } };
        var sql = TableDdl.RenderCreateTableFromFields("mysql", "`t`", fields, NoPk);
        Assert.Contains("DEFAULT 'active'", sql);
    }

    [Fact]
    public void Create_mysql_unsigned_and_comment_modifiers()
    {
        var fields = new List<FieldDto>
        {
            new FieldDto { Name = "qty", Type = "INT", Unsigned = true, Nullable = false, Comment = "amount" }
        };
        var sql = TableDdl.RenderCreateTableFromFields("mysql", "`t`", fields, NoPk);
        Assert.Contains("`qty` INT UNSIGNED NOT NULL", sql);
        Assert.Contains("COMMENT 'amount'", sql);
    }

    [Fact]
    public void Create_composite_primary_key()
    {
        var fields = new List<FieldDto>
        {
            new FieldDto { Name = "a", Type = "INT", Nullable = false },
            new FieldDto { Name = "b", Type = "INT", Nullable = false }
        };
        var sql = TableDdl.RenderCreateTableFromFields("mysql", "`t`", fields, new List<string> { "a", "b" });
        Assert.Contains("PRIMARY KEY (`a`, `b`)", sql);
    }

    [Fact]
    public void Create_no_primary_key_clause_when_empty()
    {
        var fields = new List<FieldDto> { new FieldDto { Name = "x", Type = "INT" } };
        var sql = TableDdl.RenderCreateTableFromFields("pg", "\"t\"", fields, NoPk);
        Assert.DoesNotContain("PRIMARY KEY", sql);
    }

    // End-to-end: the generated CREATE SQL must be valid SQL that actually creates the
    // table. Verified against a real sqlite file (the one DB runnable in-process).
    // Uses a non-auto-increment table — sqlite's `INT AUTOINCREMENT` inline form is a
    // known pre-existing quirk (sqlite needs INTEGER PRIMARY KEY AUTOINCREMENT).
    [Fact]
    public void Create_executes_on_real_sqlite()
    {
        var dbPath = Path.Combine(Path.GetTempPath(), $"antares_create_{Guid.NewGuid():N}.db");
        try
        {
            var cfg = ConnectionConfigBuilder.Build(new ConnectionParamsDto
            { Client = "sqlite", Host = "h", Port = 1, Database = "d", User = "u", Password = "p", DatabasePath = dbPath }, 1);
            using var db = new SqlSugarScope(cfg);

            var fields = new List<FieldDto>
            {
                new FieldDto { Name = "id", Type = "INTEGER", Nullable = false },
                new FieldDto { Name = "name", Type = "VARCHAR", CharLength = 100, Nullable = true, Default = "x" },
                new FieldDto { Name = "score", Type = "DECIMAL", NumLength = 10, NumScale = 2, Nullable = true }
            };
            var sql = TableDdl.RenderCreateTableFromFields("sqlite", "\"User\"", fields, new List<string> { "id" });
            db.Ado.ExecuteCommand(sql);

            Assert.True(db.DbMaintenance.IsAnyTable("User", false), "table created");
            var cols = db.DbMaintenance.GetColumnInfosByTableName("User", false);
            Assert.Equal(3, cols.Count);
        }
        finally { try { File.Delete(dbPath); } catch { /* ignore */ } }
    }
}
