using System.Collections.Generic;
using Antares.Server.Tables;
using Xunit;

namespace Antares.Server.IntegrationTests.Tables;

/// <summary>
/// Pure-function characterization tests for `TableDdl.RenderCreateTable` — the
/// CREATE TABLE assembly extracted from TablesWriteService.Create. Locks per-dialect
/// column rendering, composite PRIMARY KEY clause, reserved-word quoting, and the
/// auto-increment keyword (incl. the pg GENERATED ... AS IDENTITY fix).
/// </summary>
[Trait("Category", "unit")]
public sealed class TableDdlCreateTests
{
    private static List<NewColumnDef> IdNameCols(bool idAuto = true) => new()
    {
        new NewColumnDef { Name = "id", Type = "INT", Nullable = false, IsPrimary = true, AutoIncrement = idAuto },
        new NewColumnDef { Name = "name", Type = "VARCHAR(100)", Nullable = true }
    };

    [Fact]
    public void Create_mysql_backticks_autoincrement_and_pk()
    {
        var sql = TableDdl.RenderCreateTable("mysql", "`db`.`User`", IdNameCols());
        Assert.StartsWith("CREATE TABLE `db`.`User` (", sql);
        Assert.Contains("`id` INT AUTO_INCREMENT NOT NULL", sql);
        Assert.Contains("`name` VARCHAR(100)", sql);
        Assert.Contains("PRIMARY KEY (`id`)", sql);
    }

    [Fact]
    public void Create_mssql_brackets_identity_and_pk()
    {
        var sql = TableDdl.RenderCreateTable("mssql", "[dbo].[User]", IdNameCols());
        Assert.Contains("[id] INT IDENTITY(1,1) NOT NULL", sql);
        Assert.Contains("PRIMARY KEY ([id])", sql);
    }

    // The pg AUTO_INCREMENT bug: RenderColumn's pg branch returned "" for auto, so a
    // pg auto-increment column silently emitted no sequence/identity. Fixed to
    // GENERATED BY DEFAULT AS IDENTITY (type stays explicit, pg 10+).
    [Fact]
    public void Create_pg_emits_identity_for_autoincrement()
    {
        var sql = TableDdl.RenderCreateTable("pg", "\"public\".\"User\"", IdNameCols());
        Assert.Contains("\"id\" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
        Assert.Contains("PRIMARY KEY (\"id\")", sql);
    }

    [Fact]
    public void Create_pg_no_identity_when_not_autoincrement()
    {
        var sql = TableDdl.RenderCreateTable("pg", "\"public\".\"t\"", IdNameCols(idAuto: false));
        Assert.DoesNotContain("IDENTITY", sql);
    }

    [Fact]
    public void Create_sqlite_autoincrement_keyword()
    {
        var sql = TableDdl.RenderCreateTable("sqlite", "\"User\"", IdNameCols());
        Assert.Contains("\"id\" INT AUTOINCREMENT NOT NULL", sql);
    }

    [Fact]
    public void Create_composite_primary_key()
    {
        var cols = new List<NewColumnDef>
        {
            new NewColumnDef { Name = "a", Type = "INT", Nullable = false, IsPrimary = true },
            new NewColumnDef { Name = "b", Type = "INT", Nullable = false, IsPrimary = true }
        };
        var sql = TableDdl.RenderCreateTable("mysql", "`t`", cols);
        Assert.Contains("PRIMARY KEY (`a`, `b`)", sql);
    }

    [Fact]
    public void Create_no_primary_key_clause_when_none_primary()
    {
        var cols = new List<NewColumnDef> { new NewColumnDef { Name = "x", Type = "INT" } };
        var sql = TableDdl.RenderCreateTable("pg", "\"t\"", cols);
        Assert.DoesNotContain("PRIMARY KEY", sql);
    }
}
