import { Customizations } from 'common/interfaces/customizations';
import { defaults } from './defaults';
import sqlServerTypes from '../data-types/sqlserver';

export const customizations: Customizations = {
   ...defaults,
   defaultPort: 1433,
   defaultUser: 'sa',
   defaultDatabase: 'master',
   dataTypes: sqlServerTypes,
   indexTypes: ['PRIMARY', 'INDEX', 'UNIQUE'],
   foreignActions: ['RESTRICT', 'CASCADE', 'SET NULL', 'SET DEFAULT', 'NO ACTION'],
   database: true,
   collations: true,
   sslConnection: false,
   sshConnection: true,
   cancelQueries: true,
   processesList: true,
   schemas: true,
   tables: true,
   views: true,
   triggers: true,
   routines: true,
   functions: true,
   schedulers: false,
   elementsWrapper: '[',
   stringsWrapper: '\'',
   tableAdd: true,
   tableDdl: true,
   viewAdd: true,
   triggerAdd: true,
   routineAdd: true,
   functionAdd: true,
   schemaExport: true,
   schemaImport: true,
   tableSettings: true,
   tableRealCount: true,
   tableDuplicate: true,
   viewSettings: true,
   triggerSettings: true,
   routineSettings: true,
   functionSettings: true,
   indexes: true,
   foreigns: true,
   sortableFields: true,
   nullable: true,
   autoIncrement: true,
   comment: true,
   collation: true,
   triggerSql: 'T-SQL',
   procedureSql: 'T-SQL',
   functionSql: 'T-SQL'
};
