#!/usr/bin/env node
// Phase 1 orchestrator: run antares-ssh-probe (server-probes/SshCompat) once per
// cipher in tests/fixtures/ssh-cipher-list.txt against the user's SSH gateway,
// aggregate the results into docs/net-migration/ssh-cipher-matrix.md.
//
// Reads SSH gateway config from .env.test (DEV_SSH_HOST/PORT/USER/AUTH).
// .env.test is gitignored. Credentials never enter chat.

// Uses spawnSync (no shell). No exec, no command injection vector.
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PROBE_PROJ = join(ROOT, 'server-probes', 'SshCompat', 'SshCompat.csproj');
const CIPHER_LIST = join(ROOT, 'tests', 'fixtures', 'ssh-cipher-list.txt');
const OUT_DOC = join(ROOT, 'docs', 'net-migration', 'ssh-cipher-matrix.md');
const ENV_PATH = join(ROOT, '.env.test');

if (!existsSync(ENV_PATH)) {
   console.error(`✗ .env.test not found at ${ENV_PATH}`);
   console.error('  Copy .env.test.example to .env.test and fill in DEV_SSH_HOST / PORT / USER / AUTH.');
   process.exit(1);
}

const env = {};
for (const rawLine of readFileSync(ENV_PATH, 'utf8').split(/\r?\n/)) {
   const line = rawLine.trim();
   if (!line || line.startsWith('#')) continue;
   const eq = line.indexOf('=');
   if (eq < 0) continue;
   env[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
}

const host = env.DEV_SSH_HOST;
const port = env.DEV_SSH_PORT ?? '22';
const user = env.DEV_SSH_USER;
const auth = env.DEV_SSH_KEY_PATH ?? env.DEV_SSH_PASSWORD;

if (!host || !user || !auth) {
   console.error('✗ .env.test missing DEV_SSH_HOST / DEV_SSH_USER / (DEV_SSH_KEY_PATH or DEV_SSH_PASSWORD).');
   process.exit(1);
}

if (!existsSync(CIPHER_LIST)) {
   console.error(`✗ cipher list missing: ${CIPHER_LIST}`);
   process.exit(1);
}
const ciphers = readFileSync(CIPHER_LIST, 'utf8').split('\n')
   .map(l => l.trim())
   .filter(l => l && !l.startsWith('#'));

console.log(`▸ probing ${ciphers.length} cipher(s) against ${user}@${host}:${port} ...`);

const results = [];
let failures = 0;
for (const cipher of ciphers) {
   const probe = spawnSync('dotnet', [
      'run', '--project', PROBE_PROJ, '--configuration', 'Release', '--no-launch-profile',
      '--', host, port, user, auth, '--cipher', cipher, '--json'
   ], { encoding: 'utf8' });

   let parsed;
   try {
      const lastJsonLine = probe.stdout.split('\n').reverse().find(l => l.trim().startsWith('{'));
      parsed = lastJsonLine ? JSON.parse(lastJsonLine) : null;
   } catch {
      parsed = null;
   }

   if (!parsed) {
      results.push({ cipher, status: 'fail', error: probe.stderr.trim() || `exit ${probe.status}` });
      failures += 1;
      console.log(`  ✗ ${cipher}: probe gave no JSON output`);
      continue;
   }

   results.push({
      cipher,
      status: parsed.status,
      negotiatedKex: parsed.negotiatedKex ?? null,
      negotiatedCipher: parsed.negotiatedCipher ?? null,
      serverVersion: parsed.serverVersion ?? null,
      error: parsed.error ?? null
   });
   if (parsed.status !== 'pass') failures += 1;
   console.log(`  ${parsed.status === 'pass' ? '✓' : '✗'} ${cipher}: ${parsed.status}${parsed.error ? ' — ' + parsed.error : ''}`);
}

const lines = [];
lines.push('# SSH cipher / kex compatibility matrix');
lines.push('');
lines.push(`> Generated by \`pnpm probe:ssh\`. Target: \`${user}@${host}:${port}\`.`);
lines.push(`> Server: \`${results.find(r => r.serverVersion)?.serverVersion ?? '(unknown)'}\`.`);
lines.push('');
lines.push('| # | cipher / kex | status | negotiated kex | negotiated cipher | error |');
lines.push('|---|---|---|---|---|---|');
results.forEach((r, i) => {
   const tick = r.status === 'pass' ? '✅' : '❌';
   lines.push(`| ${i + 1} | \`${r.cipher}\` | ${tick} ${r.status} | ${r.negotiatedKex ?? '—'} | ${r.negotiatedCipher ?? '—'} | ${r.error ? '`' + r.error.replace(/\|/g, '\\|') + '`' : '—'} |`);
});
lines.push('');
lines.push(`**Summary**: ${results.length - failures}/${results.length} pass.`);
lines.push('');
if (failures > 0) {
   lines.push('## Fallback recommendations');
   lines.push('');
   lines.push('Failing entries above need either:');
   lines.push('- the gateway operator to enable the cipher / kex on the SSH server, OR');
   lines.push('- antares2 to fall back to the server\'s default-allowed list (no manual cipher gating).');
}

writeFileSync(OUT_DOC, lines.join('\n') + '\n');
console.log(`\n✓ ${results.length - failures}/${results.length} ciphers pass — wrote ${OUT_DOC}`);
process.exit(failures === 0 ? 0 : 1);
